// <auto-generated />
namespace TAIS_S2_Sistema_Matriculas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddSeccionFieldToModelAlumno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSeccionFieldToModelAlumno));
        
        string IMigrationMetadata.Id
        {
            get { return "201811210306474_AddSeccionFieldToModelAlumno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
